#!/bin/sh

iterations=5
num_hashes=$((1 << 20))
num_hashes_serial=$((1 << 20))
num_blocks=64
num_blocks_serial=1

for x in $(seq $iterations)
do
	for hash in sha224
	do
		./hash_benchmark $num_hashes_serial $num_blocks_serial $hash serial
		for runner in sycl-cpu sycl-gpu
		do
			./hash_benchmark $num_hashes $num_blocks $hash $runner
		done
	done
done | cut -f 2,4,6,8,10 | tee benchout-$(date '+%F-%T').tsv
